const routesScreen = {
  Home: 'Home',
  Explore: 'Explore',
  Bookmark: 'Bookmark',
  Profile: 'Profile',
  Auth: 'Auth',
  Notifications: 'Notifications',
  PickTopic: 'PickTopic',
  BottomTab: 'BottomTab',
  PostEditor: 'PostEditor',
  PostDetail: 'PostDetail',
  Comment: 'Comments',
  Settings: 'Settings',
  ProfileEdit: 'ProfileEdit',
  Search: 'Search',
  NotFound: 'NotFound',
  PostsTopic: 'PostsTopic',
  ListsTab: 'ListsTab',
  Follow: 'Follow',
  Followers: 'Followers',
  Following: 'Following',
  FollowGeneral: 'FollowGeneral',
  Login: 'Login',
  SignUp: 'SignUp',
  Verify: 'Verify',
  PasswordReset: 'PasswordReset',
};

export default routesScreen;
